apiVersion: v1
kind: Service
metadata:
  name: ticketflow-backend
  namespace: ticketflow
  labels:
    app: ticketflow-backend
spec:
  type: ClusterIP
  selector:
    app: ticketflow-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
